$:
  vscode:
    - docker:
        build: .ide/Dockerfile  # 优先用Dockerfile构建
        # image: cnbcool/default-dev-env:latest  # 备用镜像（可选）
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al